name: wordle
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.10.6

dependencies:
  flutter:
    sdk: flutter
  flutter_localization: ^0.1.12
  flutter_localizations:
    sdk: flutter
  google_fonts: ^5.1.0
  intl: 0.18.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
